apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: upstream-and-map
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: upstream-and-map
        tier: backend
        track: stable
    spec:
      containers:
        - name: upstream-and-map
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
