apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: upstream-and-map
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: upstream-and-map
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: upstream_and_map:frontend
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
