apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: upstream-and-map
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
